document.getElementById("savebutton").addEventListener("click",save);
document.getElementById("returnbutton").addEventListener("click",retrieve);
document.getElementById("maketablebutton").addEventListener("click",createTable);
const returned = document.getElementById("returned")
//object
let person = {name:""}

//saving function
function save(){
    person.name = document.getElementById("personname").value
    
    console.log("Before saving: ", person.name);
    stringname = JSON.stringify(person.name);
    localStorage.setItem("names", stringname);

}
function retrieve(){
    retrieved = JSON.parse(localStorage.getItem("names"));
    
   returned.innerHTML = retrieved;
   console.log("After retrieving: ", retrieved);

}
function createTable(){
  //this is a variable which finds the biketab tag
  const tbody = document.getElementById("biketab");

  //cycle through the data set
  for(let i = 0; i < data.length; i++){
    //this creates a floating element called row with a tr tag name <tr>
    let row = document.createElement("tr");
    //this creates a floating element called indexCell with a td tag name <td>
    let indexCell = document.createElement("td");
  }

}
//this is the data set generated by chatGPT which we need to create a table from
let data = [
  { "model": "Model-001", "gears": 21, "components": "SRAM", "tireWidth": 45, "weight": 12.4 },
  { "model": "Model-002", "gears": 14, "components": "Shimano", "tireWidth": 39, "weight": 11.2 },
  { "model": "Model-003", "gears": 18, "components": "Campagnolo", "tireWidth": 50, "weight": 13.6 },
  { "model": "Model-004", "gears": 11, "components": "Rotor", "tireWidth": 26, "weight": 9.7 },
  { "model": "Model-005", "gears": 25, "components": "Box", "tireWidth": 40, "weight": 12.9 },
  { "model": "Model-006", "gears": 30, "components": "FSA", "tireWidth": 60, "weight": 15.8 },
  { "model": "Model-007", "gears": 12, "components": "SunRace", "tireWidth": 34, "weight": 11.1 },
  { "model": "Model-008", "gears": 17, "components": "MicroSHIFT", "tireWidth": 55, "weight": 13.0 },
  { "model": "Model-009", "gears": 20, "components": "Shimano", "tireWidth": 36, "weight": 12.5 },
  { "model": "Model-010", "gears": 16, "components": "SRAM", "tireWidth": 42, "weight": 11.3 },
  { "model": "Model-011", "gears": 13, "components": "Box", "tireWidth": 31, "weight": 10.1 },
  { "model": "Model-012", "gears": 22, "components": "Rotor", "tireWidth": 38, "weight": 14.2 },
  { "model": "Model-013", "gears": 9, "components": "Campagnolo", "tireWidth": 44, "weight": 13.3 },
  { "model": "Model-014", "gears": 24, "components": "SunRace", "tireWidth": 58, "weight": 16.5 },
  { "model": "Model-015", "gears": 15, "components": "MicroSHIFT", "tireWidth": 43, "weight": 13.1 },
  { "model": "Model-016", "gears": 5, "components": "FSA", "tireWidth": 29, "weight": 8.4 },
  { "model": "Model-017", "gears": 28, "components": "Shimano", "tireWidth": 30, "weight": 10.5 },
  { "model": "Model-018", "gears": 7, "components": "SRAM", "tireWidth": 49, "weight": 13.9 },
  { "model": "Model-019", "gears": 8, "components": "Box", "tireWidth": 32, "weight": 9.8 },
  { "model": "Model-020", "gears": 27, "components": "Rotor", "tireWidth": 57, "weight": 17.2 },
  { "model": "Model-021", "gears": 10, "components": "Campagnolo", "tireWidth": 41, "weight": 12.0 },
  { "model": "Model-022", "gears": 23, "components": "SunRace", "tireWidth": 60, "weight": 15.9 },
  { "model": "Model-023", "gears": 19, "components": "MicroSHIFT", "tireWidth": 46, "weight": 14.4 },
  { "model": "Model-024", "gears": 4, "components": "FSA", "tireWidth": 28, "weight": 7.5 },
  { "model": "Model-025", "gears": 26, "components": "Shimano", "tireWidth": 33, "weight": 10.6 },
  { "model": "Model-026", "gears": 6, "components": "SRAM", "tireWidth": 52, "weight": 14.3 },
  { "model": "Model-027", "gears": 3, "components": "Box", "tireWidth": 25, "weight": 7.2 },
  { "model": "Model-028", "gears": 29, "components": "Rotor", "tireWidth": 54, "weight": 17.0 },
  { "model": "Model-029", "gears": 18, "components": "Campagnolo", "tireWidth": 45, "weight": 13.7 },
  { "model": "Model-030", "gears": 12, "components": "SunRace", "tireWidth": 37, "weight": 12.1 },
  { "model": "Model-031", "gears": 14, "components": "MicroSHIFT", "tireWidth": 40, "weight": 11.4 },
  { "model": "Model-032", "gears": 1, "components": "FSA", "tireWidth": 23, "weight": 6.5 },
  { "model": "Model-033", "gears": 30, "components": "Shimano", "tireWidth": 59, "weight": 17.8 },
  { "model": "Model-034", "gears": 11, "components": "SRAM", "tireWidth": 35, "weight": 11.6 },
  { "model": "Model-035", "gears": 20, "components": "Box", "tireWidth": 43, "weight": 13.0 },
  { "model": "Model-036", "gears": 22, "components": "Rotor", "tireWidth": 48, "weight": 14.8 },
  { "model": "Model-037", "gears": 17, "components": "Campagnolo", "tireWidth": 42, "weight": 12.8 },
  { "model": "Model-038", "gears": 13, "components": "SunRace", "tireWidth": 39, "weight": 11.9 },
  { "model": "Model-039", "gears": 16, "components": "MicroSHIFT", "tireWidth": 47, "weight": 13.4 },
  { "model": "Model-040", "gears": 2, "components": "FSA", "tireWidth": 27, "weight": 7.0 },
  { "model": "Model-041", "gears": 24, "components": "Shimano", "tireWidth": 44, "weight": 13.5 },
  { "model": "Model-042", "gears": 9, "components": "SRAM", "tireWidth": 36, "weight": 10.9 },
  { "model": "Model-043", "gears": 5, "components": "Box", "tireWidth": 30, "weight": 8.2 },
  { "model": "Model-044", "gears": 28, "components": "Rotor", "tireWidth": 56, "weight": 16.7 },
  { "model": "Model-045", "gears": 15, "components": "Campagnolo", "tireWidth": 50, "weight": 13.8 },
  { "model": "Model-046", "gears": 10, "components": "SunRace", "tireWidth": 38, "weight": 11.7 },
  { "model": "Model-047", "gears": 6, "components": "MicroSHIFT", "tireWidth": 32, "weight": 9.3 },
  { "model": "Model-048", "gears": 19, "components": "FSA", "tireWidth": 53, "weight": 15.0 },
  { "model": "Model-049", "gears": 27, "components": "Shimano", "tireWidth": 46, "weight": 14.6 },
  { "model": "Model-050", "gears": 23, "components": "SRAM", "tireWidth": 51, "weight": 15.2 },
  { "model": "Model-051", "gears": 12, "components": "Campagnolo", "tireWidth": 34, "weight": 11.0 },
  { "model": "Model-052", "gears": 14, "components": "MicroSHIFT", "tireWidth": 40, "weight": 12.3 },
  { "model": "Model-053", "gears": 29, "components": "FSA", "tireWidth": 59, "weight": 17.3 },
  { "model": "Model-054", "gears": 11, "components": "Shimano", "tireWidth": 36, "weight": 11.5 },
  { "model": "Model-055", "gears": 9, "components": "SRAM", "tireWidth": 49, "weight": 13.2 },
  { "model": "Model-056", "gears": 15, "components": "Box", "tireWidth": 41, "weight": 12.6 },
  { "model": "Model-057", "gears": 27, "components": "Rotor", "tireWidth": 54, "weight": 16.1 },
  { "model": "Model-058", "gears": 19, "components": "Campagnolo", "tireWidth": 46, "weight": 14.7 },
  { "model": "Model-059", "gears": 13, "components": "SunRace", "tireWidth": 39, "weight": 11.6 },
  { "model": "Model-060", "gears": 4, "components": "MicroSHIFT", "tireWidth": 25, "weight": 7.3 },
  { "model": "Model-061", "gears": 20, "components": "FSA", "tireWidth": 44, "weight": 13.9 },
  { "model": "Model-062", "gears": 30, "components": "Shimano", "tireWidth": 60, "weight": 17.9 },
  { "model": "Model-063", "gears": 5, "components": "SRAM", "tireWidth": 28, "weight": 8.3 },
  { "model": "Model-064", "gears": 16, "components": "Box", "tireWidth": 37, "weight": 12.0 },
  { "model": "Model-065", "gears": 8, "components": "Rotor", "tireWidth": 33, "weight": 9.5 },
  { "model": "Model-066", "gears": 17, "components": "Campagnolo", "tireWidth": 45, "weight": 13.3 },
  { "model": "Model-067", "gears": 26, "components": "SunRace", "tireWidth": 53, "weight": 16.6 },
  { "model": "Model-068", "gears": 21, "components": "MicroSHIFT", "tireWidth": 48, "weight": 14.5 },
  { "model": "Model-069", "gears": 10, "components": "FSA", "tireWidth": 30, "weight": 10.4 },
  { "model": "Model-070", "gears": 6, "components": "Shimano", "tireWidth": 27, "weight": 8.1 },
  { "model": "Model-071", "gears": 22, "components": "SRAM", "tireWidth": 50, "weight": 15.4 },
  { "model": "Model-072", "gears": 24, "components": "Box", "tireWidth": 55, "weight": 15.7 },
  { "model": "Model-073", "gears": 28, "components": "Rotor", "tireWidth": 58, "weight": 17.4 },
  { "model": "Model-074", "gears": 7, "components": "Campagnolo", "tireWidth": 35, "weight": 10.0 },
  { "model": "Model-075", "gears": 18, "components": "SunRace", "tireWidth": 42, "weight": 12.7 },
  { "model": "Model-076", "gears": 23, "components": "MicroSHIFT", "tireWidth": 47, "weight": 14.0 },
  { "model": "Model-077", "gears": 3, "components": "FSA", "tireWidth": 24, "weight": 6.9 },
  { "model": "Model-078", "gears": 25, "components": "Shimano", "tireWidth": 52, "weight": 15.6 },
  { "model": "Model-079", "gears": 12, "components": "SRAM", "tireWidth": 38, "weight": 11.8 },
  { "model": "Model-080", "gears": 14, "components": "Box", "tireWidth": 43, "weight": 12.2 },
  { "model": "Model-081", "gears": 11, "components": "Rotor", "tireWidth": 32, "weight": 10.3 },
  { "model": "Model-082", "gears": 29, "components": "Campagnolo", "tireWidth": 57, "weight": 17.6 },
  { "model": "Model-083", "gears": 20, "components": "SunRace", "tireWidth": 49, "weight": 14.9 },
  { "model": "Model-084", "gears": 1, "components": "MicroSHIFT", "tireWidth": 23, "weight": 6.6 },
  { "model": "Model-085", "gears": 13, "components": "FSA", "tireWidth": 31, "weight": 10.7 },
  { "model": "Model-086", "gears": 19, "components": "Shimano", "tireWidth": 40, "weight": 13.4 },
  { "model": "Model-087", "gears": 27, "components": "SRAM", "tireWidth": 56, "weight": 16.3 },
  { "model": "Model-088", "gears": 16, "components": "Box", "tireWidth": 46, "weight": 13.6 },
  { "model": "Model-089", "gears": 9, "components": "Rotor", "tireWidth": 34, "weight": 10.2 },
  { "model": "Model-090", "gears": 2, "components": "Campagnolo", "tireWidth": 26, "weight": 7.1 },
  { "model": "Model-091", "gears": 8, "components": "SunRace", "tireWidth": 29, "weight": 9.0 },
  { "model": "Model-092", "gears": 10, "components": "MicroSHIFT", "tireWidth": 44, "weight": 11.3 },
  { "model": "Model-093", "gears": 21, "components": "FSA", "tireWidth": 50, "weight": 15.1 },
  { "model": "Model-094", "gears": 5, "components": "Shimano", "tireWidth": 28, "weight": 8.5 },
  { "model": "Model-095", "gears": 30, "components": "SRAM", "tireWidth": 60, "weight": 18.0 },
  { "model": "Model-096", "gears": 6, "components": "Box", "tireWidth": 27, "weight": 8.0 },
  { "model": "Model-097", "gears": 22, "components": "Rotor", "tireWidth": 53, "weight": 15.5 },
  { "model": "Model-098", "gears": 17, "components": "Campagnolo", "tireWidth": 39, "weight": 12.4 },
  { "model": "Model-099", "gears": 7, "components": "SunRace", "tireWidth": 30, "weight": 9.6 },
  { "model": "Model-100", "gears": 26, "components": "Rotor", "tireWidth": 57, "weight": 16.9 }
]